project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "*.md"
    - "!README.md"
    - "!docs/"
  resources:
    - assets/_aboutme.md

filters:
  - assets/filters/obsidian-callouts.lua

format:
  html:
    theme:
      - assets/scss/catppuccin-mocha.scss
      - assets/scss/styles.scss
    toc: true
    html-math-method: katex
    include-in-header: assets/html/custom_header.html
    include-after-body: assets/html/custom_body.html

website:
  title: "Roberto Park"

  page-navigation: true
  back-to-top-navigation: true

  navbar:
    background: light
    search: true
    left:
      - icon: github
        href: https://github.com/betopark97
    right:
      - href: index.md
        text: Home
      - href: portfolio.md
        text: Portfolio
      - href: projects/projects.md
        text: Projects
      - href: notes/index.md
        text: Notes
      - href: blog/index.md
        text: Blog

  sidebar:
    - id: projects
      title: "Projects"
      collapse-level: 1
      contents:
        - text: Gallery
          href: projects/projects.md
        - text: 1. Charon Analysis
          href: projects/charon-analysis/final_deliverable.md

    - id: blog
      title: "Blog"
      contents: blog/

    - id: notes
      title: "Notes"
      collapse-level: 1
      contents:
        - notes/index.md
        - section: "Terminal"
          contents: []
        - section: "DevOps"
          contents: []
        - section: "Data Engineering"
          contents: []
        - auto: "notes/data-analysis"
        - section: "Business Intelligence"
          contents: []
        - section: "Machine Learning"
          contents: []
        - section: "AI Engineering"
          contents: []

  page-footer:
    left: "Copyright 2024, Roberto Park"
    right:
      - icon: github
        href: https://github.com/betopark97
