project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  # meta data
  title: "Roberto Park"

  # navigation
  page-navigation: true # this is for the navigation in the bottom
  back-to-top-navigation: true
  
  # footer
  page-footer: 
    left: "Copyright 2024, Roberto Park" 
    right: 
      - icon: github
        href: https://github.com/betopark97

  # sidebar
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    tools: 
      - icon: github
        href: https://github.com/betopark97

    # sidebar layout    
    contents:

      # main page
      - text: Portfolio
        href: src/index.qmd
      - text: "---"

      # manual book
      - section: "Data Analysis Manual"
        contents: 
          - text: Preface
            href: src/manual/preface.qmd
          - text: Project Setup
            href: src/manual/chapter1.qmd
          - text: Problem & Ideas
            href: src/manual/chapter2.qmd
      - text: "---"

      # my projects
      - section: "Projects"
      - text: "---"

      # my blog
      - section: "Blog"
      - text: "---"

      # my learning
      - section: Study
      - text: "---"

format:
  html:
    theme:
      light: cosmos
      dark: darkly
    toc: true

editor: visual
