---
title: "Problems & Ideas"
---

1. Assess the problem
    1. search for trends
        1. the market
        2. interest of the majority
        3. consider the colloquial wording 
    2. is it aligned with the business objective?
        1. goals of the project
        2. stakeholders and their requirements
        3. outline the scope and limitations
    3. understanding metrics
        1. what metrics do we care about?
            1. define north star metric & dimensions
                1. define and calculate each key metric
                2. identify associated key dimensions
        2. what are their values and trends?
            1. report, visualize, slice
                1. slice by time (seasonality)
                2. slice by dimensions (segmentation)
        3. what drives their movement?
            1. uncover drivers & relationships
                1. translate trends to observations
                2. report values and findings
        4. what should we do about it?
            1. recommend & communicate
                1. craft a digestible narrative
                2. communicate and present results
    4. how and what type of abstract data types will the model production handle?
        1. is the data from inside or from outside?
    5. what method to use?
        1. algorithms
        2. statistical methods
    6. how should performance be measured?
        1. dependent variable
        2. independent variables
    7. ethics
        1. make sure the AI or analysis is not discriminating
        2. preserve people’s security, privacy
        3. be transparent as to the why’s